exercise/git_exercises/onmiai/onmiai/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import index, others

app_name = "onmiai"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name="index"),
    url(r'', include("userAuth.urls")),
    url(r'^others/$', others, name="others"),
]

exercise/git_exercises/onmiai/userAuth/urls.py
from django.conf.urls import url
from .views import login, logout

app_name = "userAuth"

urlpatterns = [
    url(r'^login/$', login, name="login"),
    url(r'^logout/$', logout, name="logout"),
]

exercise/git_exercises/onmiai/userAuth/models.py
from django.db import models

# Create your models here.
class Boy(models.Model):
    nickname = models.CharField(max_length=32)
    username = models.CharField(max_length=32)
    password = models.CharField(max_length=64)

class Girl(models.Model):
    nickname = models.CharField(max_length=32)
    username = models.CharField(max_length=32)
    password = models.CharField(max_length=64)

class B2G(models.Model):
    b = models.ForeignKey(to="Boy", to_field="id", on_delete=models.DO_NOTHING)
    g = models.ForeignKey(to="Girl", to_field="id", on_delete=models.DO_NOTHING)

exercise/git_exercises/onmiai/onmiai/views.py
from django.shortcuts import render, redirect
from userAuth.models import Boy, Girl, B2G

def index(request):
    user_info = request.session.get("user_info")
    if not user_info:
        return redirect("login/")
    else:
        gender = user_info.get("gender")
        if gender == "1":
            userList = Girl.objects.all()
        else:
            userList = Boy.object.all()
        return render(request, "index.html", context={
            "user_list" : userList,
        })

def others(request):
    user_info = request.session.get("user_info")
    userId = user_info.get("user_id")
    gender = user_info.get("gender")
    if gender == "1":
        userList = B2G.objects.filter(b_id=userId).values("g__nickname")
    else:
        userList = B2G.objetcs.filter(g_id=userId).values("b__nickname")
    return render(request, "others.html", context={
        "user_list" : userList,
    })

exercise/git_exercises/onmiai/userAuth/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import Boy, Girl

# Create your views here.
def login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        gender = request.POST.get("gender")
        if gender == "1":
            obj = Boy.objects.filter(username=username, password=password).first()
        else:
            obj = Girl.objects.filter(username=username, password=password).first()

        if not obj:
            return render(request, "userAuth/login.html", context={
                "msg" : "用户或密码错误!",
            })
        else:
            request.session["user_info"] = {
                "user_id" : obj.id,
                "user_name" : obj.username,
                "nick_name" : obj.nickname,
                "gender" : gender,
            }
            return redirect("/")

    return render(request, "userAuth/login.html", context={})

def logout(request):
    userInfo = request.session.get("user_info")
    if userInfo: request.session.clear()
    return render(request, "userAuth/login.html", context={})

exercise/git_exercises/onmiai/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h3>当前用户: {{ request.session.user_info.nick_name }}</h3>
    <a href="{% url 'userAuth:logout' %}">注销</a>

    <h3>异性列表</h3>
    <a href="others/">查看和我有关系的异性</a>
    <ul>
        {% for row in user_list %}
        <li>{{ row.nickname }}</li>
        {% empty %}
        没有异性的信息
        {% endfor %}
    </ul>

</body>
</html>

exercise/git_exercises/onmiai/templates/others.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h3>当前用户: {{ request.session.user_info.nickname }}</h3>
    <a href="{% url 'userAuth:logout' %}">注销</a>

    <h3>有关系的异性列表</h3>
    <ul>
        {% for row in user_list %}
            {% if  row.g__nickname %}
                <li>{{ row.g__nickname }}</li>
            {% else %}
                <li>{{ row.b__nickname }}</li>
            {% endif %}
        {% empty %}
        没有相关的异性
        {% endfor %}
    </ul>

</body>
</html>

exercise/git_exercises/onmiai/templates/userAuth/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="{% url 'userAuth:login' %}" method="POST">
        {% csrf_token %}
        <p>用户:<input type="text" name="username"></p>
        <p>密码:<input type="password" name="password"></p>
        <p>
            性别:
                男<input type="radio" name="gender" value="1">
                女<input type="radio" name="gender" value="2">
        </p>

        <input type="submit" value="提交">{{ msg }}
    </form>
</body>
</html>